defaults:
  - /_layout_probe@layout_probe: per_layer
  - /_probe_train@probe_train: linear
  - _self_

model: lczerolens/maia-1100
report_metric: f1
dataset_mate: lczerolens/lichess-puzzles-mate-in-1
dataset_non_mate: lczerolens/tcec-boards
n_mate_train: 500
n_non_mate_train: 500
n_mate_test: 125
n_non_mate_test: 125
input_encoding: INPUT_CLASSICAL_112_PLANE_NO_HISTORY_ZEROS
