defaults:
  - _self_

dataset: lczerolens/tcec-boards
model_ids:
  - lczerolens/maia-1100
  - lczerolens/maia-1500
  - lczerolens/maia-1900
n_samples: 1024
n_test: 256
probe_epochs: 50
probe_batch_size: 64
seed: 42
