defaults:
  - /_layout_probe@layout_probe: per_layer
  - /_probe_train@probe_train: linear
  - _self_

model: lczerolens/maia-1100
report_metric_binary: f1
report_metric_move: f1
dataset_mate: lczerolens/lichess-puzzles-mate-in-3
dataset_non_mate: lczerolens/tcec-boards
n_mate_binary: 512
n_non_mate: 512
n_mate_move_train: 4096
n_mate_move_test: 512
filter_failed_only: false
move_probe_mode: full
rotate_moves: true
